// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJcmVfKBUTXVUxQ7x_XsPCjMyDvWZPcMA',
    appId: '1:1039328309765:web:1104a969dc17d13fc5a26c',
    messagingSenderId: '1039328309765',
    projectId: 'rgb-colorama',
    authDomain: 'rgb-colorama.firebaseapp.com',
    storageBucket: 'rgb-colorama.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCa-Y2NCBwZOCaARcI6gL4_OZP83f-1Ig',
    appId: '1:1039328309765:android:d645f8da2701604cc5a26c',
    messagingSenderId: '1039328309765',
    projectId: 'rgb-colorama',
    storageBucket: 'rgb-colorama.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi52SUYxl4-tIPKTNFNzzFk8y9lpOo7WY',
    appId: '1:1039328309765:ios:02216982f1823fa2c5a26c',
    messagingSenderId: '1039328309765',
    projectId: 'rgb-colorama',
    storageBucket: 'rgb-colorama.appspot.com',
    iosClientId: '1039328309765-0fs12tphdfddn5cg4knpn8knu291kqpp.apps.googleusercontent.com',
    iosBundleId: 'eth.ivancito.colorama',
  );
}
